### ISSUE TITLE
Verbose

### ISSUE THREAD

**Issue by mambax** [lindt/docker_plantuml#13]
Hi,

https://plantuml.com/faq-install says you can use `java -jar plantuml.jar -verbose sequenceDiagram.txt` to get more verbose output.

Is that possible to hand over to docker too `-verbose?`?

Dom

**Comment by ransome** [comment]
Hi,

Anything after the think/plantuml will be passed as a parameter to plantuml.jar, so for this you can do:

`cat path/to/diagram.puml | docker run --rm -i think/plantuml -verbose > path/to/output.svg`

**Comment by lindt** [comment]
@ransome : thx, perfect answer :)
