### ISSUE TITLE
!include statement not working

### ISSUE THREAD

**Issue by dr-hnje** [lindt/docker_plantuml#15]
Just wanted to know how to work with files that use the !include statement to include other files.

Any suggestions?

```
ERROR
3
cannot include Path/To/SomeModel.puml
Some diagram description contains errors
```

**Comment by ransome** [comment]
I had this same issue.  The trick is to bind the folder so it is discoverable by the plantuml.jar executable which runs from the root folder of the machine.  Example:

`cat path/to/diagram.puml | docker run --mount type=bind,source=/absolute/model/Path,target=/Path --rm -i  think/plantuml > path/to/output.svg`

In this case the /absolute/model/Path will be bound to the container under /Path and when it executes the .jar `!include Path/To/SomeModel.puml` will work

Another solution is to take the Dockerfile source and modify it to cp your model directory during build

https://docs.docker.com/storage/volumes/

**Comment by lindt** [comment]
yes, i also just mount include directories with a command like `docker run -v $(pwd)/includes:/work/includes` plantuml

**Comment by dr-hnje** [comment]
Thanks for your suggestions. I can see that I ended up using another image (miy4/plantuml) back when I needed this. I'm not sure if it was only because of using include statement, or if there were other reasons as well... I was solving a one-off task at the time.
