### ISSUE TITLE
Upgrade included version of PlantUML

### ISSUE THREAD

**Issue by mcbeelen** [lindt/docker_plantuml#19]
In order to support using C4-PlantUML, which is included in PlantUML Stdlib
I would like have an up to date version of PlantUML available in this Docker image.

**Comment by pmorch** [comment]
In the meantime

https://hub.docker.com/r/miy4/plantuml
https://github.com/miy4/docker-plantuml

is almost identical to this repo, and *does* use a newer plantuml jar.

**Comment by lindt** [comment]
now finally updated the version
